# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: array.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='array.proto',
  package='board',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x61rray.proto\x12\x05\x62oard\"i\n\x10\x41\x64\x64\x41\x64vertRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08userName\x18\x03 \x01(\t\x12\x11\n\tuserEmail\x18\x04 \x01(\t\x12\x13\n\x0b\x63reatedTime\x18\x05 \x01(\t\"!\n\x0e\x41\x64\x64\x41\x64vertReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\x18GetCountOfAdvertsRequest\"\'\n\x16GetCountOfAdvertsReply\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"\x13\n\x11GetAdvertsRequest\"1\n\x0fGetAdvertsReply\x12\x1e\n\x07\x61\x64verts\x18\x01 \x03(\x0b\x32\r.board.Advert\"_\n\x06\x41\x64vert\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08userName\x18\x03 \x01(\t\x12\x11\n\tuserEmail\x18\x04 \x01(\t\x12\x13\n\x0b\x63reatedTime\x18\x05 \x01(\t\"\x0e\n\x0c\x43learRequest\"\x1b\n\nClearReply\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32\x99\x02\n\x05\x42oard\x12=\n\tAddAdvert\x12\x17.board.AddAdvertRequest\x1a\x15.board.AddAdvertReply\"\x00\x12U\n\x11GetCountOfAdverts\x12\x1f.board.GetCountOfAdvertsRequest\x1a\x1d.board.GetCountOfAdvertsReply\"\x00\x12@\n\nGetAdverts\x12\x18.board.GetAdvertsRequest\x1a\x16.board.GetAdvertsReply\"\x00\x12\x38\n\x0c\x43learAdverts\x12\x13.board.ClearRequest\x1a\x11.board.ClearReply\"\x00\x62\x06proto3')
)




_ADDADVERTREQUEST = _descriptor.Descriptor(
  name='AddAdvertRequest',
  full_name='board.AddAdvertRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='board.AddAdvertRequest.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='board.AddAdvertRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userName', full_name='board.AddAdvertRequest.userName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userEmail', full_name='board.AddAdvertRequest.userEmail', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdTime', full_name='board.AddAdvertRequest.createdTime', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=127,
)


_ADDADVERTREPLY = _descriptor.Descriptor(
  name='AddAdvertReply',
  full_name='board.AddAdvertReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='board.AddAdvertReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=162,
)


_GETCOUNTOFADVERTSREQUEST = _descriptor.Descriptor(
  name='GetCountOfAdvertsRequest',
  full_name='board.GetCountOfAdvertsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=190,
)


_GETCOUNTOFADVERTSREPLY = _descriptor.Descriptor(
  name='GetCountOfAdvertsReply',
  full_name='board.GetCountOfAdvertsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='board.GetCountOfAdvertsReply.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=231,
)


_GETADVERTSREQUEST = _descriptor.Descriptor(
  name='GetAdvertsRequest',
  full_name='board.GetAdvertsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=252,
)


_GETADVERTSREPLY = _descriptor.Descriptor(
  name='GetAdvertsReply',
  full_name='board.GetAdvertsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adverts', full_name='board.GetAdvertsReply.adverts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=303,
)


_ADVERT = _descriptor.Descriptor(
  name='Advert',
  full_name='board.Advert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='board.Advert.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='board.Advert.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userName', full_name='board.Advert.userName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userEmail', full_name='board.Advert.userEmail', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdTime', full_name='board.Advert.createdTime', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=400,
)


_CLEARREQUEST = _descriptor.Descriptor(
  name='ClearRequest',
  full_name='board.ClearRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=416,
)


_CLEARREPLY = _descriptor.Descriptor(
  name='ClearReply',
  full_name='board.ClearReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='board.ClearReply.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=445,
)

_GETADVERTSREPLY.fields_by_name['adverts'].message_type = _ADVERT
DESCRIPTOR.message_types_by_name['AddAdvertRequest'] = _ADDADVERTREQUEST
DESCRIPTOR.message_types_by_name['AddAdvertReply'] = _ADDADVERTREPLY
DESCRIPTOR.message_types_by_name['GetCountOfAdvertsRequest'] = _GETCOUNTOFADVERTSREQUEST
DESCRIPTOR.message_types_by_name['GetCountOfAdvertsReply'] = _GETCOUNTOFADVERTSREPLY
DESCRIPTOR.message_types_by_name['GetAdvertsRequest'] = _GETADVERTSREQUEST
DESCRIPTOR.message_types_by_name['GetAdvertsReply'] = _GETADVERTSREPLY
DESCRIPTOR.message_types_by_name['Advert'] = _ADVERT
DESCRIPTOR.message_types_by_name['ClearRequest'] = _CLEARREQUEST
DESCRIPTOR.message_types_by_name['ClearReply'] = _CLEARREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddAdvertRequest = _reflection.GeneratedProtocolMessageType('AddAdvertRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDADVERTREQUEST,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:board.AddAdvertRequest)
  ))
_sym_db.RegisterMessage(AddAdvertRequest)

AddAdvertReply = _reflection.GeneratedProtocolMessageType('AddAdvertReply', (_message.Message,), dict(
  DESCRIPTOR = _ADDADVERTREPLY,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:board.AddAdvertReply)
  ))
_sym_db.RegisterMessage(AddAdvertReply)

GetCountOfAdvertsRequest = _reflection.GeneratedProtocolMessageType('GetCountOfAdvertsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCOUNTOFADVERTSREQUEST,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:board.GetCountOfAdvertsRequest)
  ))
_sym_db.RegisterMessage(GetCountOfAdvertsRequest)

GetCountOfAdvertsReply = _reflection.GeneratedProtocolMessageType('GetCountOfAdvertsReply', (_message.Message,), dict(
  DESCRIPTOR = _GETCOUNTOFADVERTSREPLY,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:board.GetCountOfAdvertsReply)
  ))
_sym_db.RegisterMessage(GetCountOfAdvertsReply)

GetAdvertsRequest = _reflection.GeneratedProtocolMessageType('GetAdvertsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETADVERTSREQUEST,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:board.GetAdvertsRequest)
  ))
_sym_db.RegisterMessage(GetAdvertsRequest)

GetAdvertsReply = _reflection.GeneratedProtocolMessageType('GetAdvertsReply', (_message.Message,), dict(
  DESCRIPTOR = _GETADVERTSREPLY,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:board.GetAdvertsReply)
  ))
_sym_db.RegisterMessage(GetAdvertsReply)

Advert = _reflection.GeneratedProtocolMessageType('Advert', (_message.Message,), dict(
  DESCRIPTOR = _ADVERT,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:board.Advert)
  ))
_sym_db.RegisterMessage(Advert)

ClearRequest = _reflection.GeneratedProtocolMessageType('ClearRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLEARREQUEST,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:board.ClearRequest)
  ))
_sym_db.RegisterMessage(ClearRequest)

ClearReply = _reflection.GeneratedProtocolMessageType('ClearReply', (_message.Message,), dict(
  DESCRIPTOR = _CLEARREPLY,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:board.ClearReply)
  ))
_sym_db.RegisterMessage(ClearReply)



_BOARD = _descriptor.ServiceDescriptor(
  name='Board',
  full_name='board.Board',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=448,
  serialized_end=729,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddAdvert',
    full_name='board.Board.AddAdvert',
    index=0,
    containing_service=None,
    input_type=_ADDADVERTREQUEST,
    output_type=_ADDADVERTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCountOfAdverts',
    full_name='board.Board.GetCountOfAdverts',
    index=1,
    containing_service=None,
    input_type=_GETCOUNTOFADVERTSREQUEST,
    output_type=_GETCOUNTOFADVERTSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAdverts',
    full_name='board.Board.GetAdverts',
    index=2,
    containing_service=None,
    input_type=_GETADVERTSREQUEST,
    output_type=_GETADVERTSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ClearAdverts',
    full_name='board.Board.ClearAdverts',
    index=3,
    containing_service=None,
    input_type=_CLEARREQUEST,
    output_type=_CLEARREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOARD)

DESCRIPTOR.services_by_name['Board'] = _BOARD

# @@protoc_insertion_point(module_scope)
